// NOTE: in the future these legal agreement templates may (or may not) be generated by a library that generates HTML, and/or be saved in the server database

export function createNDA(challengeSponsor: string, userFullName: string) {
	return [
		bold('THIS AGREEMENT IS BETWEEN:'),
		bold(
			`1. ${challengeSponsor} ("Challenge Sponsor”) and its challenge participators (collectively, “Challenge Participants”); and`
		),
		bold(`2. You, ${userFullName} ("the Judge”),`),
		bold(`collectively referred to as “the Parties”.`),
		'',
		bold(`RECITALS`),
		alphabeticList([
			'The Judge understands that the Challenge Participants have disclosed or may disclose information relating to source code, product designs, art, intellectual property, and other related concepts, which to the extent previously, presently, or subsequently disclosed to the Judge is hereinafter referred to as Proprietary Information of the Challenge Participants.',
		]),
		bold('OPERATIVE PROVISIONS'),
		numberedList([
			'In consideration of the disclosure of Proprietary Information by the Challenge Participants, the Judge hereby agrees: (i) to hold the Proprietary Information in strict confidence and to take all reasonable precautions to protect such Proprietary Information (including, without limitation, all precautions the Judge employs with respect to its own confidential materials), (ii) not to disclose any such Proprietary Information or any information derived therefrom to any third person, (iii) no to make any use whatsoever except for the purpose of evaluating or scoring the Challenge Participants submissions.',
			'The judge may disclose the Proprietary Information only independently developed without the use of any Proprietary Information of the Challenge Participants. The Judge may make disclosures required by law or court order provided the Judge uses diligent reasonable efforts to limit disclosures and has allowed the Challenge Participants to seek a protective order.',
			'When applicable: Immediately upon the written request by the Challenge Participants at any time, the Judge will return to the Challenge Participants all Proprietary Information and all documents or media containing any such Proprietary Information and any and all copies or extracts thereof, save that where such Proprietary Information is a form of incapable of return or has been copied or transcribed into another document, it shall be destroyed or erased, as appropriate.',
			'The Judge understands that nothing herein (i) requires the disclosure of any Proprietary Information or (ii) requires the Challenge Participants to proceed with any transaction or relationship.',
			'The Judge further acknowledges and agrees that no representation or warranty, express or implied, is or will be made, and no responsibility or liability is or will be accepted by the Challenge Sponsor, or by any of its respective directors, officers, employees, agents, or its advisors, it is responsible for making its own independent assessment of the Challenge Participants submissions Or Proprietary Information.',
			'The failure of either party to enforce its rights under this Agreement at any time for any period shall not be construed as a waiver of such rights. If any part, term or provision of this Agreement is held to be illegal or unenforceable neither the validity, nor enforceability of the remainder of this Agreement shall be affected. Neither Party shall assign or transfer all or any part of its rights under this Agreement without the consent of the other Party. This Agreement may not be amended for any other reason without the prior written agreement of both Parties. This Agreement constitutes the entire understanding between the Parties relating to the subject matter hereof unless any representation or warranty made about this Agreement was fraudulently and, save as may be expressly referred to or referenced herein, supersedes all prior representations, writings, negotiations, or understandings with respect hereto.',
			'This Agreement shall be governed by the laws of the jurisdiction in which the Challenge Sponsor is located )or if the Challenge Sponsor is based in more than one country, the country in which its headquarters are located) (“the Territory”) and the Parties agree to submit disputes arising out of or in connection with this Agreement to the non-exclusive of the courts in the Territory.',
		]),
	].join('\n');
}

// utils
function line(text: string) {
	return text + '\n';
}
function bold(text: string) {
	return '<strong>' + text + '</strong>';
}
function numberedList(texts: string[]) {
	return (
		'<ol class="list-decimal">' +
		texts.map((x) => '<li class="ml-4">' + x + '</li>').join('') +
		'</ol>'
	);
}
function alphabeticList(texts: string[]) {
	return (
		'<ol class="list-[upper-alpha]">' +
		texts.map((x) => '<li class="ml-4">' + x + '</li>').join('') +
		'</ol>'
	);
}
function link(text: string) {
	return '<a class="!underline !text-yellow-dark" href="/">' + text + '</a>';
}
